In [1]:
import sys

sys.path.append("..")

from src.data_extraction import Hotel_Scraper

/Users/asadbek/Documents/hotel_price_category/myenv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [2]:
hotel_scraper = Hotel_Scraper()

In [3]:
hotel_scraper.scrape_all()

Request failed: HTTPSConnectionPool(host='mybooking.uz', port=443): Max retries exceeded with url: /uz/hotels/tashkent?hotel_id=&checkin=10.07.2026&checkout=11.07.2026&adults=6 (Caused by NewConnectionError("HTTPSConnection(host='mybooking.uz', port=443): Failed to establish a new connection: [Errno 65] No route to host"))
Request failed: HTTPSConnectionPool(host='mybooking.uz', port=443): Max retries exceeded with url: /uz/hotels/bukhara?hotel_id=&checkin=10.07.2026&checkout=11.07.2026&adults=3 (Caused by NewConnectionError("HTTPSConnection(host='mybooking.uz', port=443): Failed to establish a new connection: [Errno 65] No route to host"))
Request failed: HTTPSConnectionPool(host='mybooking.uz', port=443): Max retries exceeded with url: /uz/hotels/bukhara?hotel_id=&checkin=10.07.2026&checkout=11.07.2026&adults=5 (Caused by NewConnectionError("HTTPSConnection(host='mybooking.uz', port=443): Failed to establish a new connection: [Errno 65] No route to host"))
Request failed: HTTPSConnectionPool(host='mybooking.uz', port=443): Max retries exceeded with url: /uz/hotels/fergana?hotel_id=&checkin=10.07.2026&checkout=11.07.2026&adults=4 (Caused by NewConnectionError("HTTPSConnection(host='mybooking.uz', port=443): Failed to establish a new connection: [Errno 65] No route to host"))
Request timed out: {e}
Request failed: HTTPSConnectionPool(host='mybooking.uz', port=443): Max retries exceeded with url: /uz/hotels/namangan?hotel_id=&checkin=10.07.2026&checkout=11.07.2026&adults=2 (Caused by NewConnectionError("HTTPSConnection(host='mybooking.uz', port=443): Failed to establish a new connection: [Errno 65] No route to host"))
Request timed out: {e}
Request failed: HTTPSConnectionPool(host='mybooking.uz', port=443): Max retries exceeded with url: /uz/hotels/navoi?hotel_id=&checkin=10.07.2026&checkout=11.07.2026&adults=7 (Caused by NewConnectionError("HTTPSConnection(host='mybooking.uz', port=443): Failed to establish a new connection: [Errno 65] No route to host"))
Request failed: HTTPSConnectionPool(host='mybooking.uz', port=443): Max retries exceeded with url: /uz/hotels/termez?hotel_id=&checkin=10.07.2026&checkout=11.07.2026&adults=1 (Caused by NewConnectionError("HTTPSConnection(host='mybooking.uz', port=443): Failed to establish a new connection: [Errno 65] No route to host"))
Request failed: HTTPSConnectionPool(host='mybooking.uz', port=443): Max retries exceeded with url: /uz/hotels/termez?hotel_id=&checkin=10.07.2026&checkout=11.07.2026&adults=7 (Caused by NewConnectionError("HTTPSConnection(host='mybooking.uz', port=443): Failed to establish a new connection: [Errno 65] No route to host"))
Request timed out: {e}
Request failed: HTTPSConnectionPool(host='mybooking.uz', port=443): Max retries exceeded with url: /uz/hotels/kitab?hotel_id=&checkin=10.07.2026&checkout=11.07.2026&adults=1 (Caused by NewConnectionError("HTTPSConnection(host='mybooking.uz', port=443): Failed to establish a new connection: [Errno 65] No route to host"))
Request failed: HTTPSConnectionPool(host='mybooking.uz', port=443): Max retries exceeded with url: /uz/hotels/kitab?hotel_id=&checkin=10.07.2026&checkout=11.07.2026&adults=3 (Caused by NewConnectionError("HTTPSConnection(host='mybooking.uz', port=443): Failed to establish a new connection: [Errno 65] No route to host"))
Request failed: HTTPSConnectionPool(host='mybooking.uz', port=443): Max retries exceeded with url: /uz/hotels/mujnak?hotel_id=&checkin=10.07.2026&checkout=11.07.2026&adults=1 (Caused by NewConnectionError("HTTPSConnection(host='mybooking.uz', port=443): Failed to establish a new connection: [Errno 65] No route to host"))
Request failed: HTTPSConnectionPool(host='mybooking.uz', port=443): Max retries exceeded with url: /uz/hotels/mujnak?hotel_id=&checkin=10.07.2026&checkout=11.07.2026&adults=7 (Caused by NewConnectionError("HTTPSConnection(host='mybooking.uz', port=443): Failed to establish a new connection: [Errno 65] No route to host"))

In [6]:
import pandas as pd

df = pd.read_csv("../data/cities/tashkent.csv")

In [5]:
df.head()

,title,price,adults,city,distance_to_center,description,bf_has_included
0,Haziniy Mehmonxonasi,37.46,1,tashkent,4.1,"""King-size"" o'lchamdagi to'shakli standart xona",True
1,North Star Mehmonxonasi,45.78,1,tashkent,2.3,"""Komfort"" toifasidagi ikki kishilik xona",True
2,Samanid Hotel,37.46,1,tashkent,5.7,Katta ikki kishilik xona,True
3,City Mehmonxonasi,33.71,1,tashkent,3.5,Ikkita alohida to'shakli ikki kishilik standar...,True
4,South Tashkent Mexmonxonasi,29.97,1,tashkent,6.8,Bir kishilik Delyuks xona,True

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282 entries, 0 to 281
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               282 non-null    object
 1   price               282 non-null    float64
 2   adults              282 non-null    int64
 3   city                282 non-null    object
 4   distance_to_center  282 non-null    float64
 5   description         282 non-null    object
 6   bf_has_included     282 non-null    bool
dtypes: bool(1), float64(2), int64(1), object(3)
memory usage: 13.6+ KB

In [7]:
df.tail(40)

,title,price,adults,city,distance_to_center,description,bf_has_included
242,NINETY Butik Mehmonxonasi,152.33,7,tashkent,2.4,Oilaviy xona (2 nafar katta kishilar + 1 nafar...,False
243,Arda Plaza Mehmonxonasi,120.70,7,tashkent,5.7,Standart uch kishilik xona,True
244,Barhat Mehmonxonasi,166.48,7,tashkent,3.5,Ikki xonali oilaviy xona,True
245,SOLIEF Mehmonxonasi,141.51,7,tashkent,6.6,Uch kishilik Delyuks xona,True
246,Art Deluxe Mehmonxonasi,189.79,7,tashkent,3.7,Yaxshilangan oilaviy xona,True
247,Xon Palace by Reikartz,211.43,7,tashkent,3.0,Standart uch kishilik xona,True
248,Beshchinor Mehmonxonasi,153.16,7,tashkent,2.3,Oilaviy Delyuks xona,True
249,Lakeside Mehmonxonasi,233.07,7,tashkent,2.4,Ikki xonali oilaviy xona,True
250,Old City Mehmonxonasi,83.24,7,tashkent,1.1,Oilaviy Delyuks xona,True
251,Expo Mehmonxonasi,191.45,7,tashkent,3.8,Standart uch kishilik xona,True
252,Sumaya Mehmonxonasi,121.45,7,tashkent,3.6,"To'rt kishilik xona ""Komfort""",True
253,Muhsin Mehmonxonasi,179.96,7,tashkent,6.1,Standart uch kishilik xona,True
254,AKS Mehmonxonasi,162.32,7,tashkent,11.7,Oilaviy Delyuks xona,True
255,The Art Hosteli,454.49,7,tashkent,2.3,Oilaviy xona,True
256,Home Butik Mehmonxonasi,324.63,7,tashkent,2.2,Oilaviy Delyuks xona,True
257,Art Regency Mehmonxonasi,243.24,7,tashkent,1.9,Oilaviy xona (2 nafar katta kishilar + 1 nafar...,True
258,DSF GARDEN Mehmonxonasi,199.77,7,tashkent,2.4,Standart uch kishilik xona,True
259,SADI Mehmonxonasi,151.08,7,tashkent,4.2,Uch kishilik xona + ochiladigan divan-karavot,True
260,Bo'ston Mehmonxonasi,170.64,7,tashkent,4.9,To'rt kishilik Delyuks xona,True
261,Art Air Mehmonxonasi,205.60,7,tashkent,5.2,To'rt kishilik Delyuks xona,True
262,RASODA Mehmonxonasi,241.39,7,tashkent,3.2,Standart uch kishilik xona,True
263,Velvet Tashkent Mehmonxonasi,129.02,7,tashkent,5.1,Yaxshilangan to'rt kishilik xona,True
264,Parvona Hosteli,141.51,7,tashkent,9.8,Byudjet uch kishilik xona,False
265,VEAGAT B&B Hosteli,145.67,7,tashkent,3.9,Standart uch kishilik xona,True
266,Praga Mehmonxonasi,209.98,7,tashkent,3.9,Bitta katta to'shakli ikki kishilik Delyuks xo...,False
267,Daniel Hill Mehmonxonasi,291.34,7,tashkent,8.5,Standart uch kishilik xona,True
268,Leader Mehmonxonasi,178.97,7,tashkent,2.3,Yaxshilangan uch kishilik xona,True
269,Miracle Mehmonxonasi,116.54,7,tashkent,5.4,Standart uch kishilik xona,True
270,City Line Butik Mehmonxonasi,154.16,7,tashkent,5.2,"""King-size"" to'shakli va balkonli Yarim Lyuks ...",True
271,Ak Saray Mehmonxonasi,208.10,7,tashkent,3.4,Oilaviy Delyuks xona,True
272,Semurg Mehmonxonasi,153.99,7,tashkent,3.9,Oilaviy xona,True
273,Asia Tashkent Mehmonxonasi,241.39,7,tashkent,6.2,Standart uch kishilik xona,True
274,Globus Mehmonxonasi,183.13,7,tashkent,6.7,Standart uch kishilik xona,True
275,Sapphire Mehmonxonasi,141.51,7,tashkent,3.6,"Uch kishilik xona ""Komfort""",True
276,Art Tashkent Mehmonxonasi,186.46,7,tashkent,2.3,Standart uch kishilik xona,True
277,Riverside Mehmonxonasi,74.92,7,tashkent,6.7,To'rt kishilik byudjet xona,False
278,Viva Mehmonxonasi,160.65,7,tashkent,2.8,Standart to'rt kishilik xona,True
279,Karaman Eco Hotel,141.51,7,tashkent,4.1,Oilaviy xona,True
280,Al Anvar Mehmonxonasi,324.63,7,tashkent,2.4,Yaxshilangan uch kishilik xona,True
281,Muxlis Mehmonxonasi,116.54,7,tashkent,8.5,Standart uch kishilik xona,True

In [8]:
df.shape

(282, 7)

In [9]:
hotel_scraper.merge_csv_files()

,title,price,adults,city,distance_to_center,description,bf_has_included
0,Bex Sueno Mehmonxonasi,26.55,1,samarkand,3.7,Bir kishilik Delyuks xona,True
1,AL MARYAM Mehmonxonasi,31.84,1,samarkand,1.2,Bitta katta to'shakli ikki kishilik Delyuks xona,True
2,SAM GREEN HOUSE hostel,8.32,1,samarkand,7.7,7 kishilik erkaklar uchun umumiy xona,False
3,Safi Plaza,41.62,1,samarkand,1.2,Bitta katta to'shakli ikki kishilik Delyuks xona,True
4,Azam Plaza Hotel,41.62,1,samarkand,5.0,Ikkita alohida to'shakli ikki kishilik standar...,True
...,...,...,...,...,...,...,...
1253,Al-Amin Hotel,174.80,6,termez,2.5,Bitta katta to'shakli ikki kishilik standart xona,True
1254,Reikartz Termez Palace,237.23,6,termez,1.5,Bitta katta to'shakli ikki kishilik standart xona,True
1255,Gold Palace Mehmonxonasi,187.29,6,termez,2.1,Ikkita alohida to'shakli ikki kishilik standar...,True
1256,Marshal Hosteli,54.11,6,termez,4.4,"To'rt kishilik xona ""Komfort""",True
1257,Fayz Tillo Mehmon uyi,99.89,6,termez,1.6,Uch kishilik umumiy xonada to'shak,False

In [8]:
hotels_data=pd.read_csv("../data/merged/hotels.csv")

In [11]:
hotels_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               1258 non-null   object
 1   price               1258 non-null   float64
 2   adults              1258 non-null   int64
 3   city                1258 non-null   object
 4   distance_to_center  1258 non-null   float64
 5   description         1258 non-null   object
 6   bf_has_included     1258 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(3)
memory usage: 60.3+ KB

In [17]:
hotels_data["title"].value_counts()

title
Shedevr Plaza Mehmonxonasi       10
Uzbekistan Mehmonxonasi           9
NOVA HOTEL                        7
DUNYO Jizzax                      7
One Global Oilaviy mehmon uyi     7
                                 ..
Osiyo Palace Mehmonxonasi         1
IRIS Mehmonxonasi                 1
TTT Hosteli                       1
Nur Hosteli                       1
VIRA Mehmonxonasi                 1
Name: count, Length: 297, dtype: int64

In [20]:
hotels_data["price"].describe()

count    1258.000000
mean      111.681955
std        86.658316
min         2.000000
25%        49.940000
50%        83.240000
75%       149.830000
max       790.550000
Name: price, dtype: float64

In [15]:
hotels_data["price"].mean()

np.float64(111.68195548489666)

In [16]:
hotels_data["price"].mode()

0    49.94
Name: price, dtype: float64

In [18]:
hotels_data["price"].min()

np.float64(2.0)

In [19]:
hotels_data["price"].max()

np.float64(790.55)

In [21]:
hotels_data["price_category"] = pd.qcut(
    hotels_data["price"],
    q=4,
    labels=[
        "Budget",
        "Standard",
        "Premium",
        "Luxury"
    ]
)

In [22]:
hotels_data.head()

,title,price,adults,city,distance_to_center,description,bf_has_included,price_category
0,Bex Sueno Mehmonxonasi,26.55,1,samarkand,3.7,Bir kishilik Delyuks xona,True,Budget
1,AL MARYAM Mehmonxonasi,31.84,1,samarkand,1.2,Bitta katta to'shakli ikki kishilik Delyuks xona,True,Budget
2,SAM GREEN HOUSE hostel,8.32,1,samarkand,7.7,7 kishilik erkaklar uchun umumiy xona,False,Budget
3,Safi Plaza,41.62,1,samarkand,1.2,Bitta katta to'shakli ikki kishilik Delyuks xona,True,Budget
4,Azam Plaza Hotel,41.62,1,samarkand,5.0,Ikkita alohida to'shakli ikki kishilik standar...,True,Budget

In [3]:
df=hotel_scraper.merge_csv_files()

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               1258 non-null   object
 1   price               1258 non-null   float64
 2   adults              1258 non-null   int64
 3   city                1258 non-null   object
 4   distance_to_center  1258 non-null   float64
 5   description         1258 non-null   object
 6   bf_has_included     1258 non-null   bool
 7   price_category      1258 non-null   object
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 70.2+ KB

In [5]:
df["price_category"].value_counts()

price_category
Standard    337
Luxury      327
Premium     314
Budget      280
Name: count, dtype: int64